<a href="https://colab.research.google.com/github/JohnnyAliyev/JohnnyAliyev-github.io/blob/main/13_Building_a_Personalized_Movie_Recommendation_Engine_Using_Cosine_Similarity_to_Match_User_Preferences_with_Relevant_Films.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 <a id="1"></a>
# <div style="text-align:center; border-radius:15px 50px; padding:7px; color:white; margin:0; font-size:100%; font-family:Pacifico; background-color:#284b50; overflow:hidden"><b>Building a Personalized Movie Recommendation Engine Using Cosine Similarity to Match User Preferences with Relevant Films.</b></div>

# *1.Import Libraires*

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#

# *2.Import Dataset*

In [ ]:
movies_data=pd.read_csv('/Users/maegbug/Desktop/ARTIFICIAL INTELLIGENT/Sample Datas for ML/movies.csv')
movies_data.head(16)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
5,5,258000000,Fantasy Action Adventure,http://www.sonypictures.com/movies/spider-man3/,559,dual identity amnesia sandstorm love of one's ...,en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,...,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576,Tobey Maguire Kirsten Dunst James Franco Thoma...,"[{'name': 'Francine Maisler', 'gender': 1, 'de...",Sam Raimi
6,6,260000000,Animation Family,http://disney.go.com/disneypictures/tangled/,38757,hostage magic horse fairy tale musical,en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,...,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330,Zachary Levi Mandy Moore Donna Murphy Ron Perl...,"[{'name': 'John Lasseter', 'gender': 2, 'depar...",Byron Howard
7,7,280000000,Action Adventure Science Fiction,http://marvel.com/movies/movie/193/avengers_ag...,99861,marvel comic sequel superhero based on comic b...,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,...,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767,Robert Downey Jr. Chris Hemsworth Mark Ruffalo...,"[{'name': 'Danny Elfman', 'gender': 2, 'depart...",Joss Whedon
8,8,250000000,Adventure Fantasy Family,http://harrypotter.warnerbros.com/harrypottera...,767,witch magic broom school of witchcraft wizardry,en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,...,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293,Daniel Radcliffe Rupert Grint Emma Watson Tom ...,"[{'name': 'Bruno Delbonnel', 'gender': 0, 'dep...",David Yates
9,9,250000000,Action Adventure Fantasy,http://www.batmanvsupermandawnofjustice.com/,209112,dc comics vigilante superhero based on comic b...,en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,...,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004,Ben Affleck Henry Cavill Gal Gadot Amy Adams J...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Zack Snyder
10,10,270000000,Adventure Fantasy Action Science Fiction,http://www.superman.com,1452,saving the world dc comics invulnerability seq...,en,Superman Returns,Superman returns to discover his 5-year absenc...,57.925623,...,154.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Superman Returns,5.4,1400,Brandon Routh Kevin Spacey Kate Bosworth James...,"[{'name': 'Roger Mussenden', 'gender': 2, 'dep...",Bryan Singer
11,11,200000000,Adventure Action Thriller Crime,http://www.mgm.com/view/movie/234/Quantum-of-S...,10764,killing undercover secret agent british secret...,en,Quantum of Solace,Quantum of Solace continues the adventures of ...,107.928811,...,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"For love, for hate, for justice, for revenge.",Quantum of Solace,6.1,2965,Daniel Craig Olga Kurylenko Mathieu Amalric Ju...,"[{'name': 'Paul Haggis', 'gender': 2, 'departm...",Marc Forster
12,12,200000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,58,witch fortune teller bondage exotic island mon...,en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,145.847379,...,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Jack is back!,Pirates of the Caribbean: Dead Man's Chest,7.0,5246,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
13,13,255000000,Action Adventure Western,http://disney.go.com/the-lone-ranger/,57201,texas horse survivor texas ranger partner,en,The Lone Ranger,The Texas Rangers chase down a gang of outlaws...,49.046956,...,149.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never Take Off the Mask,The Lone Ranger,5.9,2311,Johnny Depp Armie Hammer William Fichtner Hele...,"[{'name': 'Gore Verbinski', 'gender': 2, 'depa...",Gore Verbinski
14,14,225000000,Action Adventure Fantasy Science Fiction,http://www.manofsteel.com/,49521,saving the world dc comics superhero based on ...,en,Man of Steel,A young boy learns that he has extraordinary p...,99.398009,...,143.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You will believe that a man can fly.,Man of Steel,6.5,6359,Henry Cavill Amy Adams Michael Shannon Kevin C...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Zack Snyder
15,15,225000000,Adventure Family Fantasy,NaN,2454,based on novel fictional place brother sister ...,en,The Chronicles of Narnia: Prince Caspian,One year after their incredible adventures in ...,53.978602,...,150.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Hope has a new face.,The Chronicles of Narnia: Prince Caspian,6.3,1630,Ben Barnes William Moseley Anna Popplewell Ska...,"[{'name': 'Liz Mullane', 'gender': 1, 'departm...",Andrew Adamson

#

# *3.Data Analysis*

In [ ]:
movies_data.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [ ]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [ ]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
movies_data.shape

(4803, 24)

In [ ]:
features=['genres','keywords','tagline','cast','director']
features

['genres', 'keywords', 'tagline', 'cast', 'director']

In [ ]:
#replacing null values
for i in features:
    movies_data[i]=movies_data[i].fillna('')
movies_data.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

#

# *4.Data Preparing*

In [ ]:
#combine
c_features= movies_data['genres']+ movies_data['keywords']+movies_data['tagline']+movies_data['cast']+movies_data['director']
pd.DataFrame(c_features)

                                                      0
0     Action Adventure Fantasy Science Fictioncultur...
1     Adventure Fantasy Actionocean drug abuse exoti...
2     Action Adventure Crimespy based on novel secre...
3     Action Crime Drama Thrillerdc comics crime fig...
4     Action Adventure Science Fictionbased on novel...
...                                                 ...
4798  Action Crime Thrillerunited states\u2013mexico...
4799  Comedy RomanceA newlywed couple's honeymoon is...
4800  Comedy Drama Romance TV Moviedate love at firs...
4801  A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802  Documentaryobsession camcorder crush dream gir...

[4803 rows x 1 columns]

In [ ]:
# CONVERTING textual data to numerical data
vectorizer=TfidfVectorizer()
f_vectors=vectorizer.fit_transform(c_features)
print(f_vectors)

  (0, 245)	0.07858581760804864
  (0, 444)	0.09109355212252296
  (0, 8936)	0.11806131645084655
  (0, 21836)	0.09966592997173947
  (0, 9304)	0.27385789694599244
  (0, 4456)	0.2179967521551067
  (0, 10193)	0.1653243242081299
  (0, 22916)	0.3366875640692919
  (0, 26334)	0.130597230719163
  (0, 4676)	0.24529097704249617
  (0, 22778)	0.27385789694599244
  (0, 24197)	0.07518543993419267
  (0, 27161)	0.12619886579371511
  (0, 18164)	0.08690831799482268
  (0, 18558)	0.26121683351048536
  (0, 21521)	0.15623566659433683
  (0, 27182)	0.23480088356130557
  (0, 27540)	0.19771357974524179
  (0, 21487)	0.21550128478931552
  (0, 22464)	0.2020708956871175
  (0, 26547)	0.19638671147741735
  (0, 23267)	0.16128139780622522
  (0, 14550)	0.22368093636480682
  (0, 16614)	0.1569607387745327
  (0, 20729)	0.27385789694599244
  :	:
  (4801, 18790)	0.22450140828104795
  (4801, 11776)	0.3005604008026175
  (4801, 758)	0.19369913462690624
  (4801, 8121)	0.2611505149930138
  (4801, 27513)	0.3005604008026175
  (4801, 27361)	0.31510541707008866
  (4801, 22170)	0.31510541707008866
  (4801, 5449)	0.31510541707008866
  (4801, 21297)	0.31510541707008866
  (4801, 22322)	0.31510541707008866
  (4801, 12520)	0.31510541707008866
  (4802, 7626)	0.17686850692938538
  (4802, 3128)	0.17288424030654004
  (4802, 8313)	0.1713172199751922
  (4802, 5354)	0.2196244946235084
  (4802, 2027)	0.19514642661077047
  (4802, 20664)	0.1718311116708895
  (4802, 11042)	0.2245754361399493
  (4802, 5847)	0.2598601666162226
  (4802, 9174)	0.23381507827213685
  (4802, 3569)	0.2526933433912742
  (4802, 6978)	0.28212235292045307
  (4802, 10640)	0.28212235292045307
  (4802, 11874)	0.5642447058409061
  (4802, 7770)	0.28212235292045307

#

# *5. Finding silimarity*

In [ ]:
similarity=cosine_similarity(f_vectors)
# Convert to DataFrame for better readability
df_similarity = pd.DataFrame(similarity, columns=[f'Doc {i}' for i in range(f_vectors.shape[0])],
                             index=[f'Doc {i}' for i in range(f_vectors.shape[0])])

df_similarity = pd.DataFrame(similarity, columns=movies_data['title'], index=movies_data['title'])
pd.options.display.float_format = '{:.1f}'.format
df_similarity['The Dark Knight Rises'].sort_values(ascending=False)

title
The Dark Knight Rises                   1.0
The Dark Knight                         0.4
Batman Begins                           0.4
The Prestige                            0.2
Interstellar                            0.2
                                         ..
ATL                                     0.0
Pitch Perfect                           0.0
They                                    0.0
Larry the Cable Guy: Health Inspector   0.0
My Date with Drew                       0.0
Name: The Dark Knight Rises, Length: 4803, dtype: float64

In [ ]:
movies_data['title'].head()

0                                      Avatar
1    Pirates of the Caribbean: At World's End
2                                     Spectre
3                       The Dark Knight Rises
4                                 John Carter
Name: title, dtype: object

In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name :  Batman

Movies suggested for you :

1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . Batman Begins
5 . Man of Steel
6 . Beetlejuice
7 . Mars Attacks!
8 . Superman Returns
9 . Jonah Hex
10 . The Dark Knight Rises
11 . Superman III
12 . Bedazzled
13 . A History of Violence
14 . Reds
15 . I Dreamed of Africa
16 . The Dark Knight
17 . Superman
18 . Something's Gotta Give
19 . Exorcist II: The Heretic
20 . Superman II
21 . Blood and Wine
22 . The New Guy
23 . Catwoman
24 . 8 Mile
25 . Nine 1/2 Weeks
26 . Batman
27 . Batman Forever
28 . Multiplicity
29 . Cellular